services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=1
      - MAPBOX_ENC_KEY=${MAPBOX_ENC_KEY}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/api/docs/"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - eldnet

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - eldnet

networks:
  eldnet:
    driver: bridge
