# Generated by Django 5.2.6 on 2025-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="mapbox_api_key_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
    ]
