# Generated by Django 5.2.6 on 2025-09-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_mapbox_api_key_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="carrier_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_state",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="terminal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="time_zone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="driver",
            name="truck_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="units",
            field=models.CharField(
                choices=[("miles", "Miles"), ("km", "Kilometers")], default="miles", max_length=8
            ),
        ),
    ]
