# Generated by Django 5.2.6 on 2025-09-17 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_mapbox_api_key_encrypted"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("license_state", models.CharField(blank=True, max_length=2)),
                ("driver_initials", models.CharField(blank=True, max_length=8)),
                ("driver_signature", models.TextField(blank=True)),
                ("home_center_city", models.CharField(blank=True, max_length=128)),
                ("home_center_state", models.CharField(blank=True, max_length=2)),
                ("carrier", models.CharField(blank=True, max_length=255)),
                ("time_zone", models.CharField(blank=True, max_length=32)),
                (
                    "units",
                    models.CharField(
                        choices=[("MILES", "Miles"), ("KM", "Kilometers")],
                        default="MILES",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
