# Generated by Django 5.2.6 on 2025-09-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driverprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="home_terminal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="main_office_address",
            field=models.TextField(blank=True),
        ),
    ]
