# Generated by Django 5.2.6 on 2025-09-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driver_carrier_name_driver_dark_mode_and_more"),
        ("drivers", "0004_driverprofile_home_terminal_address_and_more"),
    ]

    operations = []
