# Generated by Django 5.2.6 on 2025-09-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="logevent",
            new_name="logs_logeve_trip_id_e54cba_idx",
            old_name="logs_logev_trip_id_6f4b6f_idx",
        ),
        migrations.RenameIndex(
            model_name="logevent",
            new_name="logs_logeve_driver__35c312_idx",
            old_name="logs_logev_driver__e8d28a_idx",
        ),
        migrations.RenameIndex(
            model_name="logevent",
            new_name="logs_logeve_timesta_d78206_idx",
            old_name="logs_logev_timesta_7d9d7b_idx",
        ),
    ]
