# Generated by Django 5.2.6 on 2025-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logs",
            "0002_rename_logs_logev_trip_id_6f4b6f_idx_logs_logeve_trip_id_e54cba_idx_and_more",
        ),
        ("trips", "0002_trip_route_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logevent",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="logevent",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="logevent",
            name="state",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("total_off", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("total_sleeper", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("total_driving", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("total_on_duty", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["day"],
                "indexes": [
                    models.Index(fields=["trip", "day"], name="logs_dailyl_trip_id_76486e_idx"),
                    models.Index(fields=["driver", "day"], name="logs_dailyl_driver__da458c_idx"),
                ],
                "unique_together": {("trip", "driver", "day")},
            },
        ),
    ]
