# Generated by Django 5.2.6 on 2025-09-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_logevent_activity_logevent_city_logevent_state_and_more"),
        ("trips", "0002_trip_route_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PRE_TRIP", "PRE_TRIP"), ("POST_TRIP", "POST_TRIP")],
                        max_length=16,
                    ),
                ),
                ("performed_at", models.DateTimeField()),
                ("defects", models.JSONField(default=list)),
                ("signature_driver", models.CharField(max_length=255)),
                ("signature_mechanic", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(fields=["trip", "kind"], name="logs_inspec_trip_id_0f2df7_idx"),
                    models.Index(fields=["driver"], name="logs_inspec_driver__2367df_idx"),
                ],
            },
        ),
    ]
