# Generated by Django 5.2.6 on 2025-09-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("distance_miles", models.DecimalField(decimal_places=2, max_digits=8)),
                ("estimated_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fueling_stops", models.JSONField(default=list)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time", models.DateTimeField(blank=True, null=True)),
                ("route_geometry", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
