# Generated by Django 5.2.6 on 2025-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_route_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="co_driver_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="commodity_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="load_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="trip",
            name="log_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="other_trailers",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="shipper_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="tractor_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="trip",
            name="trailer_numbers",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
