# Generated by Django 5.2.6 on 2025-09-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_route_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLANNED",
                max_length=16,
            ),
        ),
    ]
