# Generated by Django 5.2.6 on 2025-09-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_co_driver_name_trip_commodity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="license_plate",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="trip",
            name="license_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_mileage_today",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_miles_driving_today",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
