# Generated by Django 5.2.6 on 2025-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="status",
        ),
    ]
