# Generated by Django 5.2.6 on 2025-09-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_trip_license_plate_trip_license_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="license_plate",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="license_state",
        ),
    ]
