# Generated by Django 5.2.6 on 2025-09-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_remove_trip_status"),
        ("trips", "0005_remove_license_fields"),
    ]

    operations = []
